### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-wallet-connect#2]
- [x] Readme (include a code of conduct and contributing guide section)
- [x] DCO
- [x] Licence file
- [x] Licence headers

- [ ] SonarQube
- [x] Github actions
- [x] Code Coverage
- [x] Branch protection rules
- [ ] ~~Add project to Hedera docs site when live (if required)~~
- [ ] ~~Standardize package name (com.hedera.<name>) (if applicable)~~
- [x] Add [security.md](http://security.md/) file if the project is not going to be part of the bug bounty program
- [ ] ~~Approval from council (if required)~~
- [ ] ~~Code audit before open sourcing (If required)~~

- [ ] Open source project

**Comment by gregscullard** [comment]
Repo open sourced, closing this issue
